name: Docker Image rsnapshot CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * 0'
#weekly
  

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
#      -
#        name: Set up QEMU
#        uses: docker/setup-qemu-action@v1
#      -
#        name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: andreaskasper
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push 1
        uses: docker/build-push-action@v2
        with:
          context: rsnapshot/.
          push: true
          tags: andreaskasper/rsnapshot:latest
      -
        name: Build and push 2
        uses: docker/build-push-action@v2
        with:
          context: rsnapshot/.
          push: true
          tags: andreaskasper/rsnapshot:debian
